//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Okuyucular
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Okuyucular()
        {
            this.ÖdünçKitaplar = new HashSet<ÖdünçKitaplar>();
            this.ÖdünçKitaplar1 = new HashSet<ÖdünçKitaplar>();
        }
    
        public int OkuyucuId { get; set; }
        public string OkuyucuAd { get; set; }
        public string OkuyucuSoyad { get; set; }
        public string OkuyucuKod { get; set; }
        public string OkuyucuMail { get; set; }
        public string OkuyucuTelefon { get; set; }
        public string OkuyucuCinsiyet { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ÖdünçKitaplar> ÖdünçKitaplar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ÖdünçKitaplar> ÖdünçKitaplar1 { get; set; }
    }
}
